version: '3'
services:
  node:
    image: node:12-alpine
    working_dir: /project
    volumes:
      - ./:/project
    environment: 
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY